version: '3.8'

services:
  orchestrator:
    build:
      context: .
      dockerfile: orchestrator.Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env

  agent:
    build:
      context: .
      dockerfile: agent.Dockerfile
    env_file:
      - .env
    depends_on:
      - orchestrator

